server:
  port: 8001
spring:
  redis:
    host: 192.168.188.145
    port: 6379
    password: 123456
  session:
    store-type: redis #session存储方式
    timeout: 1800     #session过期时间 单位：秒
  #开始thymeleaf设置
  thymeleaf:
    #禁用模板缓存
    cache: false
hgjklkk
aaaaaaaaaaaaaaaa
